ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"


rdo:
  # project_release: epoxy (X)     # https://releases.openstack.org/
  # project_release: bobcat
  # release_name: caracal
  release_name: dalmatian
  cluster_name: jack-kr-rdo
  domain: "jtest.pivotal.io"
  major_version: "1"
  minor_version: "31"
  patch_version: "0"
  build_version: ""
  repo_url: ""
  download_url: ""
  download: false
  base_path: /root
  host_num: "{{ groups['all'] | length }}"
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    vipaddr: "192.168.2.79"
    ipaddr0: "192.168.0.18"
    ipaddr2: "192.168.2.18"
  client:
    net:
      type: "virtual"              # Or Physical
      ipaddr0: "192.168.0.18"
      ipaddr2: "192.168.2.18"
  ext_storage:
    net:
      ipaddr0: "192.168.0."
      ipaddr2: "192.168.2."
  swift:
    devices: [ "/dev/vdd", "/dev/vde" ]
  vms:
    rk9: [ "rk9-freeipa", "rk9-node01", "rk9-node02", "rk9-node03", "rk9-node04", "rk9-node05" ]
    ubt24: [ "rk9-freeipa", "ubt24-node01", "ubt24-node02", "ubt24-node03", "ubt24-node04", "ubt24-node05" ]
  debug_opt: ""  # --debug


vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"

