- hosts: localhost

  tasks:
    - name: "{{ power_title }} Virtual Machines Without the Answer Param"
      vmware_guest_powerstate:
        hostname: "{{ vmware.esxi_hostname }}"
        username: "{{ vmware.esxi_username }}"
        password: "{{ vmware.esxi_password }}"
        validate_certs: false
        name: "{{ item }}"
        state: "{{ power_state }}"
      loop:
        - "co9-node01"
        - "co9-node02"
        - "co9-node03"
        - "co9-node04"
        - "co9-node05"
        - "co9-node06"
        - "co9-node07"
        - "rk9-freeipa"
      # - "rk9-node01"
      # - "rk9-node02"
      # - "rk9-node03"
      # - "rk9-node04"
      # - "rk9-node05"
      # - "rk9-node06"
      # - "rk9-node07"
      # - "VMware vCenter Server"
      # - "rk8-node01"
      # - "rk8-node02"
      # - "rk8-node03"
      # - "ubt22-rdo01"
      # - "ubt22-rdo02"
      # - "ubt22-rdo03"
      # - "VMware vCenter Server"
      # - "ubt22-rdo01"
      # - "ubt22-rdo02"
      # - "ubt22-rdo03"


