- name: Enable NetworkManager
  service: name=NetworkManager enabled=yes
  ignore_errors: true


- name: Delete Netplan Scripts
  become_user: root
  file:
    path: "/etc/netplan/{{ item }}"
    state: absent
  register: delete_netplan_scripts
  ignore_errors: true
  with_items:
    - "01-netcfg.yaml"
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
- debug: msg={{ delete_netplan_scripts }}
  when: print_debug == true and ( ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian' )


#- name: Uninstall Sysinit Network Scripts
#  dnf:
#    name: openstack-network-scripts
#    state: absent
#  ignore_errors: true

