---
- name: Configure IP Address with Netplan
  become_user: root
  template:
    src: "{{ item }}.j2"
    dest: "/etc/netplan/{{ item }}"
    mode: 0644
  register: configure_netplan_scripts
  with_items:
    - "01-netcfg.yaml"
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
- debug: msg={{ configure_netplan_scripts }}
  when: print_debug == true and ( ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian' )


- name: Disable NetworkManager
  service: name=NetworkManager enabled=no
