---
- name: Install Devstack Controller Node
  become_user: stack
  shell: |
   ./stack.sh
  ignore_errors: true
  args:
    chdir: /opt/stack/devstack
    executable: /bin/bash
  when: inventory_hostname in groups['controller']


- name: Install Devstack Compute Nodes
  become_user: stack
  shell: |
   ./stack.sh
  ignore_errors: true
  args:
    chdir: /opt/stack/devstack
    executable: /bin/bash
  when: inventory_hostname in groups['compute']

