---
- name: Check OS ( Devstack )
  fail: msg="{{ ansible_os_family }} is not OS supported for This ansible Playbook"
  when: ansible_os_family != 'Debian' or ansible_os_family != 'Ubuntu'


- name: Set Facts for Package Name and List and Network Range
  import_tasks: set-devstack-facts.yml
  tags: prepare, install, uninstall, create, delete, deploy, destroy, config, deconfig, exec


- name: Prepare Devstack Environment
  import_tasks: prepare-devstack.yml
  tags: prepare, install
  when: ( env is defined and env == true ) or ( devstack_all is defined and devstack_all == true )


- name: Get Devstack Git Sources
  import_tasks: get-devstack-git-sources.yml
  tags: setup, prepare, config, install
  when: ( source is defined and source == true ) or ( devstack_all is defined and devstack_all == true )


- name: Configure Devstack Controller
  import_tasks: configure-controller.yml
  tags: config, setup
  when: (( controller is defined and controller == true ) or ( devstack_all is defined and devstack_all == true )) and inventory_hostname in groups['controller']


- name: Configure Devstack Compute
  import_tasks: configure-compute.yml
  tags: config, setup
  when: (( compute is defined and compute == true ) or ( devstack_all is defined and devstack_all == true )) and inventory_hostname in groups['compute']


- name: Install Devstack Controller
  import_tasks: install-controller.yml
  tags: install, deploy
  when: (( controller is defined and controller == true ) or ( devstack_all is defined and devstack_all == true )) and inventory_hostname in groups['controller']


- name: Install Devstack Compute
  import_tasks: install-compute.yml
  tags: install, deploy
  when: (( compute is defined and compute == true ) or ( devstack_all is defined and devstack_all == true )) and inventory_hostname in groups['compute']


#- name: Install Devstack
#  import_tasks: install-devstack.yml
#  tags: install, deploy
#  when: ( osp is defined and osp == true ) or ( devstack_all is defined and devstack_all == true )


- name: Uninstall Devstack
  import_tasks: uninstall-devstack.yml
  tags: uninstall, destroy
  when: (( osp is defined and osp == true ) or ( devstack_all is defined and devstack_all == true ))


- name: Disable Zabbly Repo
  import_tasks: disable-zabbly-repo.yaml
  tags: disable, delete
  when: ( repo is defined and repo == true )


- name: Reboot Devstack Hosts
  import_tasks: reboot-hosts.yml
  tags: exec
  when: ( reboot is defined and reboot == true )

