---
- name: Uninstall Devstack
  become_user: stack
  shell: |
    ./unstack.sh
  register: uninstall_devstack
  until: uninstall_devstack is succeeded
  retries: 5
  delay: 30
  ignore_errors: true
  args:
    chdir: /opt/stack/devstack
    executable: /bin/bash
- debug: msg={{ uninstall_devstack }}


- name: Clean Devstack
  become_user: stack
  shell: |
    ./clean.sh
  register: clean_devstack
  ignore_errors: true
  until: clean_devstack is succeeded
  retries: 5
  delay: 30
  args:
    chdir: /opt/stack/devstack
    executable: /bin/bash
- debug: msg={{ clean_devstack }}


- name: Disable Legacy Network
  import_tasks: network/disable-legacy-network.yml


- name: Start Firewalld
  service: name=firewalld state=started enabled=no
  ignore_errors: true


- name: Kill Processes Hold On User Directory
  become: true
  shell: |
    {{ item }}stack
    sleep 3
  register: kill_user_processes
  until: kill_user_processes is succeeded
  retries: 10
  with_items:
    - "nohup pkill -U "
    - "nohup fuser -k /opt/"


- name: Remove Stack Git Sources
  file: path=/opt/stack state=absent
  register: remove_git_dir
- debug: msg={{ remove_git_dir }}


- name: Remove Stack User
  user:
    name: stack
    shell: /bin/bash
    home: /opt/stack
    state: absent
    remove: true
  ignore_errors: true
    # group: stack


- name: Reboot Required
  shell: ( /bin/sleep 5; /sbin/shutdown -r now "Ansible updates triggered" ) &
  register: reboot_required
  ignore_errors: true
  async: 120
  poll: 0
  notify:
    - Waiting for Server to Come Back After Reboot


- meta: flush_handlers

