---
#- name: Copy Uninstall RDO Script
#  become_user: root
#  template:
#    src: "{{ item }}.j2"
#    dest: "/root/{{ item }}"
#    mode: 0755
#  register: copy_uninstall_el9s_script
#  ignore_errors: true
#  with_items:
#    - "remove-el9s-pkgs.sh"
#- debug: msg={{ copy_uninstall_el9s_script }}


#- name: Remove EL9s RDO Packages Remained
#  shell: |
#    ./remove-el9s-pkgs.sh
#  ignore_errors: true
#  args:
#    chdir: /root/
#    executable: /bin/bash


- name: Enable SELinux Policy
  import_tasks: enable-selinux.yml


- name: Disable Legacy Network
  import_tasks: disable-legacy-network.yml


- name: Flush IPtables
  become_user: root
  shell: |
    iptables -F
    /sbin/iptables-save > /etc/sysconfig/iptables
    cat /etc/sysconfig/iptables
  ignore_errors: true
  args:
    executable: /bin/bash


- name: Start Firewalld
  service: name=firewalld state=started enabled=no
  ignore_errors: true


- name: Remove Stack User
  user:
    name: stack
    shell: /bin/bash
    home: /opt/stack
    state: absent
    remove: true
    # group: stack


- name: Reboot Required
  shell: ( /bin/sleep 5; /sbin/shutdown -r now "Ansible updates triggered" ) &
  ignore_errors: true
  register: reboot_required
  async: 120
  poll: 0
  notify:
    - Waiting for Server to Come Back After Reboot


- meta: flush_handlers


