---
- name: Run Packstack to Deploy OpenStack
  shell: packstack --answer-file={{ rdo.base_path }}/rdo-scripts/rdo-answer.txt
  register: run_packstack
  ignore_errors: true
  when: inventory_hostname in groups['control']
- debug: msg={{ run_packstack }}
  when: print_debug == true and inventory_hostname in groups['control']
#  shell: packstack --allinone --provision-demo=n --provision-ovs-bridge=n --debug -t 3600


