---
- name: Configure IP Address with Netplan
  become_user: root
  template:
    src: "{{ item }}.j2"
    dest: "/etc/netplan/{{ item }}"
    mode: 0644
  register: configure_netplan_scripts
  with_items:
    - "01-netcfg.yaml"
  notify:
    - Disable NetworkManager
- debug: msg={{ configure_netplan_scripts }}
  when: print_debug == true

